### ISSUE TITLE
Minor things in the demo notebooks

### ISSUE THREAD

**Issue by expectopatronum** [groupmm/libsoni#11]
Hi,

first I would like to apologize that I immediately created a pull request (I only read the "Contributing" part afterwards, I am really sorry!). I cannot delete the pull requests, I could just close them but I do not want to create more mess.

I just noticed two minor things in the demo notebooks:
- demo_spectrogram.ipynb: the description says `libsoni.core.spectrum` instead of `libsoni.core.spectrogram` (twice in this notebook)
- demo_tse.ipynb: the description says `libsoni.tse` instead of `libsoni.core.tse`

Best regards
Verena

**Comment by yiitozer** [comment]
Thank you, I accepted your pull requests!
